# AI Agent Model Configuration

# Default config
# agent_model:
#   name: "gpt-5.1" # "gpt-4o"                     # Model name
#   base_url: null                          # null for default OpenAI endpoint
#   api_key_env: "OPENAI_API_KEY"          # Environment variable containing API key

# Using EPFL's inference server
agent_model:
  name: "openai/gpt-oss-120b"
  base_url: "https://inference.rcp.epfl.ch/v1"
  api_key_env: "EPFL_API_KEY"           # Set EPFL_API_KEY in .env